name: 手动-全量用户数据采集
on:
  workflow_dispatch:
    inputs:
      max_workers:
        description: '最大并发线程数'
        required: false
        default: '2'
        type: choice
        options:
          - '1'
          - '2'
          - '3'
      batch_size:
        description: '每批处理用户数'
        required: false
        default: '50'
        type: number

jobs:
  full_crawl:
    runs-on: ubuntu-latest

    steps:
    - name: 检出代码
      uses: actions/checkout@v4

    - name: 设置Python环境
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: 执行全量爬取任务
      env:
        # 数据库（优先使用 DB_*，向后兼容 MYSQL_PASSWORD）
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PORT: ${{ secrets.DB_PORT }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD || secrets.MYSQL_PASSWORD }}
        # 兼容旧密钥名（代码仍支持 MYSQL_PASSWORD）
        MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD || secrets.DB_PASSWORD }}
        # 爬虫配置
        RSS_HUB_URL: ${{ secrets.RSS_HUB_URL }}
        RSS_HUB_TOKEN: ${{ secrets.RSS_HUB_TOKEN }}
      run: |
        python3.12 main.py --task full_crawl --max-workers ${{ github.event.inputs.max_workers || '2' }}
