name: Keepalive Workflow

on:
  schedule:
    - cron: '0 0 1 * *' # Run at 00:00 on day-of-month 1.
  workflow_dispatch:

permissions:
  actions: write # Required for the action to make API calls to keep the workflow active
  contents: write # Required for checkout and if the action needs to push commits

jobs:
  keepalive:
    name: Keepalive
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v2
